### ISSUE TITLE
XML Format Commit Hook for tmc file

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-twincat-motion#13]
It's impossible to read and review the tmc file and some of the other files as is. We need a commit hook that updates a human-readable version for review purposes.

See discussion in #10

**Comment by klauer** [comment]
For future reference, I solved this in a gist: https://gist.github.com/klauer/a1489e408042a95ed9e804e37e7832c2

It was met with indifference overall, so I think we can close this. Perhaps it could be taken up by ads-deploy in the future.
