### ISSUE TITLE
Configure default names for DUT_PositionState instances of in/out positioners

### ISSUE THREAD

**Issue by klauer** [pcdshub/lcls-twincat-motion#144]
`FB_PositionStateInOut`
https://github.com/pcdshub/lcls-twincat-motion/blob/b06601abf7178475651e279f94becbe4ec9926bf/lcls-twincat-motion/Library/POUs/Motion/States/Examples/FB_PositionStateInOut.TcPOU#L17-L20

Projects which do not configure these have invalid names:
```bash
$ caget -S AT2L0:XTES:MMS:02:STATE:01:NAME_RBV AT2L0:XTES:MMS:02:STATE:02:NAME_RBV  AT2L0:XTES:MMS:02:STATE:03:NAME_RBV
AT2L0:XTES:MMS:02:STATE:01:NAME_RBV Invalid
AT2L0:XTES:MMS:02:STATE:02:NAME_RBV Invalid
AT2L0:XTES:MMS:02:STATE:03:NAME_RBV Invalid
```

Arguably the project should be specific about the state names, but I think we can probably agree that it would be sensible for the motion library to provide sensible defaults.

This matters more now that pcdsdevices (and typhos) will rely on these PVs for drop-down menus in typhos and such.

cc @ZLLentz @ZryletTC

**Comment by ZLLentz** [comment]
I think this is already handled for in/out? Am I missing something?
https://github.com/pcdshub/lcls-twincat-motion/blob/b06601abf7178475651e279f94becbe4ec9926bf/lcls-twincat-motion/Library/POUs/Deprecated/FB_EpicsInOut.TcPOU#L57-L58

**Comment by ZLLentz** [comment]
Well this is actually a bit confusing because there are two versions of in/out: the "Deprecated" one linked here and the newer one at: https://github.com/pcdshub/lcls-twincat-motion/blob/master/lcls-twincat-motion/Library/POUs/Motion/States/Examples/FB_PositionStateInOut.TcPOU

**Comment by ZLLentz** [comment]
It looks like it is this newer version that fails to mandate some basic default name values

**Comment by klauer** [comment]
The non-deprecated version could be considered in the wrong spot, though the comments do note:

https://github.com/pcdshub/lcls-twincat-motion/blob/b06601abf7178475651e279f94becbe4ec9926bf/lcls-twincat-motion/Library/POUs/Motion/States/Examples/FB_PositionStateInOut.TcPOU#L7

**Comment by ZLLentz** [comment]
The non-deprecated version definitely needs a fix as per this issue, but the link in the issue text is to the wrong file

**Comment by klauer** [comment]
My apologies - I'll fix that now.
