### ISSUE TITLE
Add helper functions for setting up state positions

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-twincat-motion#176]
## Current Behavior

No such helpers exist, and setting state position specifications manually is verbose and error-prone.

## Expected Behavior

We should create helpers that help us set up `ST_PositionState` individual instances and full state arrays.

The single struct version should let us define some defaults once and then apply them to individual position state instances, giving the user an easy way to say e.g. "each of these has a delta of 0.5, a velo of 1, (etc.)" and then set the positions and pmps keys individually.

The array version should be similar but could also let us express set positions in an array (?)

## Context / environment

We want to make the process of setting up states easier and less error-prone.

**Comment by ZLLentz** [comment]
I'm going to brainstorm straight in this comments section since I'll tackle this tomorrow, I have a second open PR that I don't want to branch from, and I want to implement it before the first "tag with nd states" so that it's available right away.

Problem statement brainstorm:

A typical setup would be something like:

```
VAR
    // States for motor 1
    aStates1: ARRAY[0..GeneralConstants.MAX_STATES] OF ST_PositionState
    // States for motor 2
    aStates2: ARRAY[0..GeneralConstants.MAX_STATES] OF ST_PositionState
    // States for motor 3
    aStates3: ARRAY[0..GeneralConstants.MAX_STATES] OF ST_PositionState
END_VAR
```

Filling this in manually looks like:
```
aStates1[1].sName := "OUT";
aStates1[1].fPosition := 20;
aStates1[1].fDelta := 20;
aStates1[1].bValidState := TRUE;
<snip>
aStates1[2].sName := "YAG";
aStates1[2].fPosition := 25;
aStates1[2].fDelta := 20;
aStates1[2].bValidState := TRUE;
<snip>
aStates2[1].sName := "OUT";
aStates2[1].fPosition := 30;
aStates2[1].fDelta := 20;
aStates2[1].bValidState := TRUE;
```

So, we have:
- some fields that are typically the same across all states (fDelta, bValidState)
- some fields that are always the same across same-indexed states (sName)
- some fields that are basically never the same across states (fPosition)
- we need to make sure we don't fill in unused states

The helpers should reduce our footprint here and let us be less redundant.

**Comment by ZLLentz** [comment]
Idea 1:
```
FUNCTION_BLOCK FB_PositionStateDefaults
(* Set input values to each state in the array up to nStates *)
VAR_IN_OUT
    astPositionState: ARRAY[1..GeneralConstants.MAX_STATES] OF ST_PositionState;
END_VAR
VAR_INPUT
    nStates: UINT;
    sName: STRING;
    fPosition: LREAL;
    // etc
END_VAR
```
This could be used like:
```
VAR
    fbDefaults: FB_PositionStateDefaults := (
        nStates := 4,
        fDelta := 0.5,
        fVelocity := 10,
        bMoveOk := TRUE,
        bValid := TRUE
    );
END_VAR
```
```
fbDefaults(astPositionState := aStates1);
fbDefaults(astPositionState := aStates2);
fbDefaults(astPositionState := aStates3);
// Then, do the individual state things
```
Which saves us from needing to repeat the common fields, at the cost of declaring one extra function block and calling it once per state array.

**Comment by ZLLentz** [comment]
I think the only thing needed on top of the above is something to help with the `sName` field, which is nice to have consistent among the multiple arrays. It should match across the arrays on index. I'll start with idea 1 and then experiment with ways to handle the names.

**Comment by klauer** [comment]
Could you also extend fbDefaults to be like: "take in these defaults except for what I override with these parameters", e.g.,
```
fbDefaults(astPositionState := aStates1, sName:='OUT', fPosition:=25);
```

**Comment by ZLLentz** [comment]
> Could you also extend fbDefaults to be like: "take in these defaults except for what I override with these parameters", e.g.,

I think so... I need to be a bit careful with the implementation though.

For example, if I leave it as intended in my head (simplest: just set all the values each time the function block is run), then by changing one of the original defaults in an fbDefaults call, you'll change it for future calls of fbDefaults. Omitting a VAR_INPUT is the same as "use the last value given", right?

So, I'd want to do it a different way- one of duplicating all the fields, having the user pass a full "template" ST_PositionState, or including an ST_PositionState as an input that can be set to, e.g.

```
fbDefaults.nStates := 4;
fbDefaults.stDefault.fDelta := 0.5,
fbDefaults.stDefault.fVelocity := 10,
fbDefaults.stDefault.bMoveOk := TRUE,
fbDefaults.stDefault.bValid := TRUE

fbDefaults(astPositionState:=aStates1, fDelta:=25);
```

Any maybe then it's possible to extend a step further as you've suggested, which requires some adjustment to the signature... and some thought... Maybe the correct thing to do is to singularize the VAR_IN_OUT as you've implicitly done. I think the FB would want a rename too and wouldn't need a state count any more:

```
// Probably can do this part more concisely
fbSetState.stDefault.fDelta := 0.5,
fbSetState.stDefault.fVelocity := 10,
fbSetState.stDefault.bMoveOk := TRUE,
fbSetState.stDefault.bValid := TRUE

// One function block call per state, all on one line instead of spread everywhere
fbSetState(astPositionState := aStates1[1], sName:='OUT', fPosition:=25);
fbSetState(astPositionState := aStates1[2], sName:='YAG', fPosition:=35);
fbSetState(astPositionState := aStates1[3], sName:='PM', fPosition:=45);
fbSetState(astPositionState := aStates1[4], sName:='TT', fPosition:=55);
```

**Comment by klauer** [comment]
I see - that makes a lot of sense. Seems like you've got enough to start with the prototyping as you've noted 👍
