### ISSUE TITLE
New NC Error Code: Decimal 19207

### ISSUE THREAD

**Issue by jsheppard95** [pcdshub/lcls-twincat-motion#76]
Recently found error code from working with MR1K2.

Decimal 19207: "Timeout axis function block"

There are lots of details in the NC manual: https://drive.google.com/file/d/1UbD8BHoNJck6DdvYdxcK9b6sH20Xi_hC/view

But in summary, this is the check to ensure a given move has completed. It will check the "AxisHasJob" flag by default and will wait for feedback from NC if either "Position Range Monitoring" or "Target Position Monitoring" are active. In any case, if the set point position is at the target but the "AxisHasJob" flag is high (or there is no feedback from NC) for more than 6 seconds, this error is thrown.

**Comment by ZLLentz** [comment]
closed by #75 and available in `v1.2.0`
